-- STATES -- 
INSERT INTO cities(name) VALUES ('Adelaide');
INSERT INTO cities(name) VALUES ('Brisbane');
INSERT INTO cities(name) VALUES ('Canberra');
INSERT INTO cities(name) VALUES ('Darwin');
INSERT INTO cities(name) VALUES ('Hobart');
INSERT INTO cities(name) VALUES ('Perth');
INSERT INTO cities(name) VALUES ('Melbourne');
INSERT INTO cities(name) VALUES ('Sydney');

-- ATTRACTIONS BY CITY -- 

-- Adelaide -- 
INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Barossa Valley Wineries Tour', 149 ,1,'Visit South Australia’s Barossa Valley wine region on this day trip from Adelaide that includes tastings at four wineries, plus a winery lunch. With a guide, discover Peter Lehmann, Chateau Yaldara and Langmeil Winery for a well-rounded winery experience that introduces you to varietals from both established and newer wine producers. Learn insider facts about winemaking in this renowned region, and stop by other attractions like the Whispering Wall and Mengler’s Hill Lookout. This tour is limited to 20 people.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0a/dc/53/0d.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Kangaroo Island Day-Tour', 323 ,1,'Travel from Adelaide to Kangaroo Island, one of Australia’s most popular wildlife destinations, on this activity-filled day trip by ferry and coach. On the island, discover its natural attractions and local animals, from Vivonne Bay and Seal Bay Conservation Park to the Remarkable Rocks, Flinders Chase National Park, Admirals Arch and more. Spot wallabies, echidnas, fur seals, koalas and, of course, kangaroos.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/71/98/7c.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('McLaren Vale Winery Tour', 200 ,1,'Taste local wine at the best wineries in McLaren Vale on this small-group tour from Adelaide, with all transportation provided. Appreciate the wine samples without the worry of having to drive. Experience the scenery of your sojourn through the Fleurieu Peninsula. Lunch is included with a glass of wine. Groups are limited to 10 for an intimate experience.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/70/23/f9.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Murray River Day Trip', 172 ,1,'Travel from Adelaide to the historic Murray River on an 8-hour day trip that includes a lunch-time cruise, a great way for first-time visitors to orient themselves. Afterwards, you will take in the Murray River landscape from the coach, stopping for photo ops and sweeping views. Visit a chocolate factory and cheese maker in Woodside on the return journey to Adelaide. Hotel pickup and drop-off are included. Please note: Effective from May 3, 2018, due to roadworks on Frome Street, the temporary pick-up location for guests staying at the Majestic Roof Garden Hotel and Mantra on Frome will be 16, Hindmarsh Square, Adelaide.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/71/98/8d.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Kayak Tour in Adelaide Dolphin Sanctuary', 72 ,1,'It’s not every day that you get the opportunity to paddle your way through a 10,000 year old mangrove forest seeing dolphins along the way and kayaing up close to shipwrecks, relics of a bygone era. It’s a special experience that simply can’t be replicated, which is why Dolphin Sanctuary Kayak Tours is a must-do!', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0d/07/8f/15.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Dolphin Sanctuary Kayaking in Adelaide', 69 ,1,'Paddle through a trail of shipwrecks and natural mangroves that make up the Adelaide Dolphin Sanctuary. We are often greeted by a pod of friendly port river dolphins that spend a large part of their day playing around in these waters. Our instructors know the best spots in the park and will guide you there with ease to give you the most enjoyable adventure you can have!', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0b/31/c2/26.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Adelaide Hills Tour w/ River Murray 3 Hour Lunch Cruise', 154 ,1,'Enjoy a relaxing half-day cruise on the Murray River aboard the paddle wheeler “Captain Proud.” Learn about the river’s history, culture, and ecosystem from the live commentary. Look out for birds and wildlife, including kangaroos, pelicans, galahs, and cockatoos. Feast on a two-course lunch while watching the world go peacefully by.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/09/48/d4/0a.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Barossa Valley Hot Air Balloon Ride with Breakfast', 330 ,1,'Watch the sunrise over the Barossa Valley, then tuck into a gourmet breakfast on this memorable 5-hour tour, including hotel pick-up. Take to the skies for a 1-hour hot air balloon flight and enjoy thrilling aerial views over the sweeping vineyards. Then, toast your safe landing with a hearty breakfast of regional specialties, accompanied by sparkling wine.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/73/d1/3a.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Hop-On Hop-Off Barossa Valley Wine Region Tour', 70 ,1,'Discover the highlights of the Barossa Valley wine region on a full-day hop-on hop-off winery tour from Adelaide. Explore at your own pace when you hop off at your choice of 10–12 wineries and eateries on the route. The full circuit takes about one hour to complete, and you will have time to hop on or off at the selected stops. Sample the wine and food options (own expense) at your leisure before returning to Adelaide in the late afternoon.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/6c/2f/4d.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Unique Trike Barossa Valley Half Day Private Tour For 2', 219 ,1,'Take a private 3.5-hour trike tour of the Barossa Valley that can be customized to your interests. Via headsets in the helmet you can hear your driver-guide’s commentary as you travel to top sights and stop to sample the region’s great food and wine. You might visit Maggie Beer’s Farm Shop, Barossa Valley Cheese Company, and breweries and wineries.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/73/26/b5.jpg');

-- Brisbane -- 
INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Moreton Island Day Trip (Kayak, Snorkel & Sandboard)', 149 ,2,'Spend a blissful day on Moreton Island exploring the beaches, snorkel sites, and enormous sand dunes during this full-day tour from Brisbane, the Sunshine Coast, or the Gold Coast. Travel with an experienced guide in a rugged 4-wheel drive vehicle, going from sea to sand as you snorkel at the Tangalooma Wrecks and kayak around the coral reef, then head inland to try sandboarding on the dunes. Enjoy a picnic lunch on the beach and soak in the tropical scenery of Moreton Island on this fun-filled tour. Please note: An additional cost of AU$50pp is to be paid in cash to your driver prior to departure to cover national park and ferry fees during this tour.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/c1/40/85.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Croc Express to Australia Zoo', 110 ,2,'Observe amazing animals from Down Under and around the world at the famous Australia Zoo—Home of the Crocodile Hunter! The legacy of Steve Irwin and his family, this conservation center aims to educate visitors about wildlife and help preserve endangered species for the future. Ride to the zoo from your Brisbane or Gold Coast hotel in an air-conditioned Croc Express coach, and enjoy hours of free time to browse the fantastic mammal, bird, and reptile exhibits. Watch supervised educational demonstrations by animal handlers.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/09/73/a3/9c.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('All Inclusive Dolphin and Tangalooma Wrecks Cruise', 179 ,2,'Throw your swimwear into a bag and set sail to Moreton Island, a world-renowned destination for encountering dolphins, dugong, and turtles. Located just 75 minutes from Brisbane, this full-day tour features an eco-cruise, tropical buffet lunch, island beach time and guided snorkel tour at the famous Tangalooma Wrecks. Board the brand new AUD 4mill vessel, the Spirit of Migaloo II, and you’ll soon discover that there’s more to Moreton Island than meets the eye.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0a/74/df/ad.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Evening Rainforest & Glow Worm Experience - Small Group Tour', 99 ,2,'Experience the nighttime enchantment of Mt Tamborine National Park on this unique 4WD rain forest walk and glowworm tour. At the mountain summit, stop for a light supper of cakes and hot chocolate, and soak up views of the twinkling Gold Coast from a lookout. Then, observe nocturnal wildlife by torchlight with a guided bushwalk through the rain forest, where you’ll come across an ethereal waterfall illuminated by glowworms.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/70/05/06.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Natural Bridge & Springbrook Waterfalls Tour', 99 ,2,'Journey into the hinterlands on this 5-hour afternoon tour of the Springbrook National Park from the Gold Coast. Explore the UNESCO-listed Goondawanna rainforests by coach, stopping to walk through the jungle, peek into ancient caves and enjoy views of Mount Warning from the Best of All Lookout.  Visit natural wonders like Purling Brook Falls, Numinbah valley and Rainbow Falls, and soak up the scenery from the Canyon Lookout. This small-group tour is limited to 16 people for a personalised experience, and includes hotel pick-up and afternoon tea.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/70/05/09.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Brisbane Story Bridge Adventure Climb', 138 ,2,'Take your adventurous spirit to new heights on a Brisbane Story Bridge Adventure day or night climb. After a safety briefing, follow an experienced climbing guide from the central platform to the summit, then cross the width of the Story Bridge. Hear audio commentary about Brisbane`s surroundings and enjoy panoramic views of the Brisbane River, Moreton Bay, the Glass House Mountains, distant Mt. Coot-tha, and Lamington National Park. Bonus: one complimentary group photo of your climb!', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/01/37/04.jpg');


INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Deluxe Winery Tour to Tamborine Mountain, includes gourmet two course lunch', 168 ,2,'Taste award-winning liqueurs, spirits, and wine on this tour of the Mt. Tamborine area, which also includes a gourmet lunch. Taste the bounty of the Great Brisbane region, including locally produced cheese from Witches Chase Cheese Factory, spirits from Tamborine Mountain Distillery, and vintages from multiple wineries. All tastings, snacks, and beverages provided means a seamless, belly-filling experience.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/6c/3e/45.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Full Day Mount Tamborine Winery Tour', 179 ,2,'Benefit from a small-group tour as you discover the wines, food, and natural beauty of Mount Tamborine on this full-day tour from Brisbane. Visit five wineries for guided tastings of 6-10 wines at each stop, sample the cheeses at Witches Chase Cheese, and enjoy a 2-course winery lunch. Try tastings of fudge, macadamias, and distillery drinks, and have time for shopping at the Gallery Walk.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/6e/c5/45.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Private Helicopter Scenic Tour of Brisbane', 230 ,2,'It can be easy to miss the forest for the trees when you’re visiting a big city like Brisbane – driving around the city in taxis and buses, it can be easy to forget that there’s more to this metropolis than just skyscrapers and shopping malls. Take in the city from the sky on this scenic helicopter tour from east to west. Fly around the towering suburban mountains Coot-Tha and Gravatt, see the Brisbane River winding through the city center, and get bird’s-eye views of sights like the Gabba and the Kangaroo Point Cliffs.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/09/9b/cd/91.jpg');

-- Canberra -- 
INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Building + Architecture Tour (10am + 2pm Daily)', 15 ,3,'Get the most out of your visit to the National Museum of Australia by joining a guided tour of its highlights. An expert guide will take you to some of the most significant items and displays in the museum, and tell you stories about their meaning and history. You’ll gain a greater insight into contemporary Australia through learning about its past.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/09/b2/e2/26.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Canberra Small Group Winery Tour', 211 ,3,'The Canberra wine region is known for its cool-climate wines, boutique wineries, and artisan producers. With this tour, dive into Canberra’s wine and foodie scene as you explore the vineyards. Visit two wineries and a distillery to sample a selection of different wines, tuck into a tasty one-course lunch, and sample decadent sweet treats at a local chocolatier.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0b/22/5a/d4.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Private Canberra Secrets Highlights Tour', 998 ,3,'This private Canberra Secrets Highlights tour takes in the city sights, with the added benefit of expertise of author and award-winning Canberra expert, Marg Wade. You’ll also discover ‘secrets’ and lots of interesting stories. Sit back, relax, and enjoy a fun day on Canberra`s best quality tour. In this time of COVID recovery, national attractions need to be booked ahead of time. Let Canberra Secrets take the hassle out of your visit. We will do your bookings and plan your itinerary for you. You can be secure knowing that your tour is private – there are no other passengers on your tour — your COVID safety is important to us. You just need to sit back, relax and enjoy your Canberra Secrets tour.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/90/78/83.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Canberra - Murrumbateman Private Group Winery Tours', 668 ,3,'This service is managed by Ibuzz International and it network partners. Our drivers are experienced, friendly and caring. This is an exclusive private group tour. It is designed to be fun to maximise the experience of the guests. The driver has experiences in wine tour around Australia from Margaret River, Swan Valley, Barossa Valley, Clare Valley, Mclaren Vale, Mornington Peninsula, Yarra Valley, Heathcote, King Valley, Rutherglen, Hunter Valley and now Murrumbateman.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/09/a8/c6/46.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Twilight Tour', 60 ,3,'Our Box Gum Grassy Woodlands ecosystem has been widely destroyed across Australia, threatening the animals that call it home. Mulligans flat offers a sanctuary for animals that have not been found on mainland Australia for up to a century. Find Eastern Bettongs, Quolls, and even the mysterious Bush Stone Curlew.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/c1/dc/f3.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('CanBEERa Explorer: Capital Brewery Full-Day Tour', 181 ,3,'Learn about Canberra’s brewing tradition with a visit to three craft breweries and a craft beer pub. Meet local brewers, learn about craft beer production, tour the breweries, and of course, taste a variety of local beers and ciders. The tour includes water, snacks, and a delicious lunch with options including burgers, schnitzel, and more.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/73/e3/90.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Capital 3in3 - 3 Craft Beer Hotspots in 3 Hours', 149 ,3,'Beer lovers will enjoy this relaxed tour that visits three Canberra craft beer hotspots in three hours. With transportation included, you don’t need to worry about getting around after a drink (or several). As this is an afternoon tour, you can continue the merriment into the evening with your new friends. There’s a limit of ten participants, so everyone will get personalized attention from the expert local guide.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/73/e3/94.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Electric Scooter Daily Self-Hire through Canberra', 65 ,3,'Hire an Electric Scooter from WalkSmart! Ride around at speeds of 25km/h throughout Canberra unrestricted! Battery range up to 60km, with an included charger so you can charge at a cafe or your hotel room! With an electric scooter hired from WalkSmart you can explore the key sites in Canberra with ease and lock the eScooter outside while you explore.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0b/d1/1b/74.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Canberra - Southern Highlands Winery Tour', 540 ,3,'This service is managed by Ibuzz International and it network partners. Our drivers are experienced, friendly and caring. This is an exclusive private group tour. It is designed to be fun to maximise the experience of the guests. The driver has experiences in wine tour around Australia from Margaret River, Swan Valley, Barossa Valley, Clare Valley, Mclaren Vale, Mornington Peninsula, Yarra Valley, Heathcote, King Valley, Rutherglen, Hunter Valley and now Murrumbateman.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0a/52/fb/00.jpg');

-- Darwin -- 
INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Sunset 3-Hour Cruise from Darwin with Dinner and Sparkling Wine', 145 ,4,'Ensure you get the best sunset vista by heading out onto the water on this cruise across Darwin Harbour. Aboard a large, ocean-going catamaran with plenty of deck space, sit under the sails or in the air-conditioned salon and toast the setting sun with a glass of sparkling wine before enjoying a tapas/barbecue dinner while soaking up the views—if you wish, you can bring your own drinks and keep them chilled in the on board coolers.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/6e/b5/6e.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Litchfield and Jumping Crocodiles Full Day Trip', 195 ,4,'Discover the best of Litchfield National Park on a full-day tour from Darwin. Head to the Adelaide River for a private Jumping Crocodile cruise that gives you great views of the crocs. Continue into Litchfield National Park to cool off in swimming holes such as Florence Falls, Wangi Falls or Buley Rockhole, see the sculptural termite mounds and have a picnic lunch. Back in Darwin, watch the sunset at Mindil Beach while sipping a glass of champagne and nibbling prawn appetizers before returning to your hotel.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0a/d5/8c/54.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Katherine Day Tour from Darwin including Katherine Gorge Cruise', 309 ,4,'Take a full-day detour from Darwin to explore the beautiful natural playground of Katherine Gorge. Cruise between ancient sandstone cliffs for an up-close perspective of Aboriginal rock art and crocodiles lounging on the riverbanks. Take a dip in a natural swimming hole at the base of Edith Falls, and recharge with a delicious picnic lunch. Get a glimpse of local cattle culture on a coach tour of Katherine, and pass through the historic gold mining town of Pine Creek.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/3d/89/ee.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Litchfield National Park and Jumping Crocodile Cruise', 185 ,4,'One of the Northern Territory`s key attractions is its isolation, but an increasing number of visitors means that the Territory`s most popular attractions are becoming very busy. Cruise the Adelaide River without bumping into lots of other groups on this early-morning tour, with the chance to swim in picturesque rock pools and meet a crocodile without a horde of onlookers spoiling the experience.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/74/c2/f5.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Darwin Harbour Sunset Cruise', 69 ,4,'Take in Darwin Harbour during a 2sunset cruise aboard the Charles Darwin, a deluxe 3-level catamaran that was built for service on the Gold Coast Broadwater. Travel past Stokes Hill Wharf, the Esplanade, Larrakeyah Naval barracks, Cullen Bay, and Fannie Bay, while seated in air-conditioned comfort or outside on the Sun Deck (top deck). Hear live commentary on Darwin’s history and landmarks, and have the option to include a buffet dinner, or purchase snacks and drinks at the onboard bar.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0b/e5/1d/38.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Litchfield National Park Day Tour from Darwin With Waterfalls And Buley Rockhole', 210 ,4,'Explore the tropical wilderness of the Litchfield National Park on this full-day small-group tour from Darwin. Visit the Florence and Wangi Falls; cool off with a dip in the Buley Rockhole, and snap photos of the gigantic Cathedral and Magnetic Termite Mounds. You`ll also enjoy a crocodile-spotting cruise along the Adelaide River and hear about the reptiles from the wildlife guide. Includes lunch, snacks, croc cruise, and hotel pickup and drop-off.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/a2/71/78.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Top End Safari Camp Day Tour', 395 ,4,'If you want to fit in all of the quintessential Top End activities into the one day then this is the tour for you! With a helicopter, airboat, cruise boat and crocodile safe swimming cafe there is no better way to experience the spectacular local wildlife and landscapes of the Litchfield region. Guests will see the majestic floodplains from above in a scenic helicopter flight and spot crocodiles, birds and even buffalo on a thrilling airboat ride through the channels and into the rainforest. Our cruise boat takes guests along Sweets Lagoon billabong for a slower pace perfect for birdwatching and taking pictures whilst tucking into a gourmet BBQ meal. We have Australia’s only nature-based croc safe pool where guests can take a dip and get face to face with a wild saltwater crocodile. The tour finishes off with an exciting feeding and exhibition with one of our rescue monster crocodiles caught by Matt Wright himself.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0b/31/7a/9a.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Helicopter Pub Crawl Tour', 990 ,4,'On this tour, you will arrive at four different kinds of watering holes where you will share a tale and beverage (or two) with the local publicans. Flying by helicopter, this pub-crawl, not only offers spectacular sights of the Top End but also has you arrive with your own rock star landing at a selection of Darwin’s handpicked iconic pubs!', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/09/36/e9/d3.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Bombing of Darwin World War II Tour with Harbour Cruise', 129 ,4,'Explore the World War II sites of Darwin on this city sightseeing and cruise tour. Visit the Darwin war memorial and East Point Military Precinct, and explore Darwin Military Museum to chart the city’s wartime experience. Midway through, enjoy a small-boat cruise around Darwin Harbour, passing the modern naval base and the remnants and wreck sites of Japan’s devastating February 1942 air raids. Hotel pickup, entrance fees, and live onboard commentary included.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/6f/43/31.jpg');

-- Hobart -- 
INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Tasman Island Cruises and Port Arthur Historic Site Day Tour', 270 ,5,'Experience the Tasman Peninsula by both land and sea on this day trip from Hobart that includes a 3-hour cruise along the coast of Tasman National Park. Gaze up at towering sea cliffs, look for wildlife like falcons and seals, and learn about the peninsula’s ecosystem. Then visit the World Heritage–listed Port Arthur Historic Site for an in-depth look at Australia’s penal history at this former convict colony. Lunch is included.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/6f/02/29.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Bruny Island Day Tour, Includes Lunch and Exclusive Lighthouse Tour', 215 ,5,'Explore Bruny Island on this full-day trip from Hobart. Travel by ferry to the island, look out for seals and penguins as you sail. On the island, admire natural sights like The Neck and Truganini Lookout, and take leisurely walks to look for wallabies and other local wildlife. Discover the island’s food scene with tastings of cheese, chocolate, cider, and oysters, plus a lunch of local produce. An exclusive group tour of the historic Cape Bruny Lighthouse completes your experience.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/09/4a/f9/a8.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Bruny Island Traveller - Gourmet Tasting and Sightseeing Day Trip', 210 ,5,'Discover the gourmet delights of Bruny Island during an all-inclusive tour full-day food tour with a knowledgeable guide who takes you to meet the local producers. You can expect enough food and drink to satisfy a hearty appetite, enjoying seven courses that include oysters, award winning cheeses, local honey, mead and chocolates. Soak in the island’s breathtaking scenery during visits to the Bruny Island Neck, historic Two Tree Point in Adventure Bay, white-sand beaches and nature reserves where rare white wallabies live.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/35/ff/18.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Full-Day Bruny Island Cruises Day Tour', 235 ,5,'Admire Bruny Island by both land and sea on this day trip from Hobart that includes a 3-hour eco-cruise around the island. You’ll have the chance to see remote beaches, rugged coastlines and native wildlife like dolphins and fur seals as you cruise past steep cliffs and deep sea caves. Ferry transport to the island is included, plus morning tea and lunch on the island.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/6f/02/1b.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Full-Day Guided Bruny Island Tour', 125 ,5,'Discover the scenic coastline, beaches, national parks, flora, and fauna of Bruny Island on this full-day tour from Hobart. Travel via ferry to the island (tickets included), and walk through the temperate rain forest, visit the Cape Bruny Lighthouse, stop at a viewing platform at the Neck, and sample locally made products.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/6c/75/19.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Derwent River Historic Harbour Cruise', 28 ,5,'Enjoy Hobart from the water on Derwent River cruise. Choose your preferred time of day for your cruise, including lunch and dinner options, and then glide through the city to admire the harbor and waterfront attractions such as the Royal Tasmanian Botanical Gardens, the Tasman Bridge, Government House, Montagu Bay, and Rose Bay.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/73/fc/f0.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Hobart Hop-on Hop-off Bus Tour', 35 ,5,'Book a 1- or 2-day pass on a Hobart hop-on hop-off bus tour for an easy way to explore the city`s top attractions at your own pace. Travel by double-decker red bus to 20 stops around the city, where you can hop off whenever you wish to visit the places that interest you. Or opt to stay onboard the bus for the full loop.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/09/2d/08/a0.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Mount Wellington Descent Cycling Tour departs Hobart', 95 ,5,'Experience the natural beauty of the Hobart region on a downhill bike tour from the summit of Mt Wellington. With a guide, you’ll start your bike ride at the top of the mountain, elevation 4,160 feet (1,270 meters), where you can marvel at the panoramic view of the city and surrounding scenery before hopping on your bike and heading down the hill, pedaling all the way back to sea level. Select a departure time when booking.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/71/11/14.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Day Tour in Mt. Field, Mt. Wellington, Bonorong Wildlife Sanctuary and Richmond', 159 ,5,'Visit some of the top attractions outside of Hobart on this day trip to Mount Wellington, Mount Field National Park, Bonorong Wildlife Sanctuary, and the historical town of Richmond. Entry fees are included for a hassle-free experience.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0b/26/ef/23.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('30-Minute Hobart Scenic Flight', 229 ,5,'Be amazed by aerial views of Hobart from a scenic 30-minute flight by seaplane. Whether you are a resident or a visitor you will be impressed by views of the rugged cliffs, beaches of Bruny Island, the Tasman Bridge, and Mt. Wellington. End with a dramatic and memorable landing on the river, before returning to Franklin Wharf.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/f2/1a/ab.jpg');

-- Perth -- 
INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Pinnacles Desert Sunset Stargazing Tour', 165 ,6,'The otherworldly landscapes of the Pinnacles Desert are one of Western Australia’s most impressive natural wonders, found just north of Perth in the Nambung National Park. On this tour, admire the Pinnacles at their most magical during a sunset visit, enjoy a sunset dinner in the desert, and stay after-dark for a thrilling stargazing experience. Along the way, stop to try sandboarding at the famous Lancelin Sand Dunes, take a guided walk along the banks of Moore River where your tour guide will show plants used by the Aborigines for food and medicine.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/c4/dd/00.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Discover Rottnest with Ferry & Bus Tour from Perth or Fremantle', 129 ,6,'Visit Perth’s favorite local getaway destination on a day trip to Rottnest Island, located just offshore in the Indian Ocean. Travel to Rottnest by high-speed ferry from either Perth or Fremantle (your choice), and then embark on a sightseeing tour of the island by coach. While you listen to narration from an informative guide, check out landmarks like the West End and Wadjemup Lighthouse. Then enjoy free time in the afternoon to explore the car-free island at your leisure. You may upgrade when booking to include lunch.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/b3/32/3e.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Dolphin, Penguin and Sea Lion Cruise', 65 ,6,'Wild dolphins, rare Australian sea lions, pelican rookeries, and birds of prey are regularly sighted and our friendly crew will get you right amongst the action! The cruise concludes on Penguin Island to see the penguin feeding and then enjoy some island time before returning on the ferry at your own leisure.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0a/db/d9/d4.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Margaret River, Caves, Wine and Cape Leeuwin Lighthouse Tour', 225 ,6,'Explore southwestern highlights on this diverse full-day tour to the Margaret River winemaking region from Perth. Along the way, visit the record-setting Busselton Jetty and Cape Leeuwin Lighthouse, where the Indian and Southern Oceans meet. Enjoy a platter lunch and cider samples at a boutique brewery, and stop at a historic winery to taste the region’s renowned vintages. You also learn about the area’s ancient geologic history as you wander through the magnificent formations of Mammoth Cave.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/9f/a6/d7.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Experience Rottnest with Ferry & Bike Hire from Perth or Fremantle', 109 ,6,'Take a day trip to Rottnest Island, a popular Perth getaway due to its white-sand beaches, secluded bays, scenic bike paths and vehicle-free atmosphere. Travel to the island, just off the coast, by high-speed ferry, and then explore at your leisure with included bike rental. Some options are snorkeling or following the trails to West End, Wadjemup or Bathurst Longhouses, the pink salt lakes or include lunch at Karma Rottnest. When booking, select the option that corresponds to your departure location—either Perth or Fremantle.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/b3/32/57.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Swan Valley Gourmet Wine Cruise', 185 ,6,'Cruise through the Swan River Valley from Perth for a relaxing day on the water that includes a stop at a local winery. Take in views of Perth and the riverfront scenery of the upper Swan River while snacking on morning and afternoon tea, and enjoy wine tastings on board the boat before visiting Sandalford Winery for a behind-the-scenes tour and 2-course lunch with more wine tastings. On the return cruise, listen to live entertainment.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/38/d1/86.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Rottnest Island Roundtrip Fast Ferry from Hillarys Boat Harbour', 94 ,6,'Escape the city for the offshore paradise of Rottnest Island, one of Perth’s most popular holiday resorts. Board your high-speed ferry from Hillarys Boat Harbour and soak up the scenery on an exhilarating 40-minute cruise across the Indian Ocean. Enjoy a full day to explore the car-free island independently, take in the views from the Wadjemup Lighthouse, hire a bike or relax on the sandy beaches. When it’s time to leave, simply head back to the jetty to catch your return ferry.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0e/10/a3/ed.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Fremantle Lunch Cruise', 80 ,6,'Spend lunch on the water during this Swan River cruise from Perth. As you glide leisurely down the river from the city to Fremantle, a historical port city located where the river meets the Indian Ocean, feast on a buffet hot dishes, salads, fruit and more. While you eat, take in views of Perth’s waterfront suburbs and yacht clubs.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0e/0c/b3/5a.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Private Sandboard and Quad Bike Adventure in Lancelin', 139 ,6,'2.5 hours ATV & UTV Adventure Tours Sandboarding in Lancelin is a must do for your bucket list, so how about adding 1.30 hours buggy or quad bike ride to this! The ultimate adventure that covers all Lancelin Sand dunes accessible by ATV or UTV (quad bike and buggy). For an adrenaline-fueled, blood-pumping experience join us on our 2.5 hours tour to enjoy the ride through the spectacular Lancelin sand dunes and get unlimited time to enjoy the thrill of sliding down the sand dunes. Choose from our range of ATV & UTV Get your adrenaline pumping nonstop as you ride through the dunes and enjoy the most beautiful beaches of Western Australia. With proper preparation and a confident spirit, you can push your riding skills to the limit as you drift around the sand dune negotiate your way in and around the landscape, emerging with lasting memories of you and your mean machine ruling Lancelin Sand Dunes.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/90/8e/69.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Kings Park Segway Tour', 129 ,6,'Segways are a fun way to cover a lot of ground without getting too tired while you`re sightseeing. This segway tour of Perth`s Kings Park will take you along bush trails, to the botanic gardens, and other special places in this beloved park. Admire the views of the Perth skyline from lookout points and see more than you would strolling around independently.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/36/00/42.jpg');

-- Melbourne -- 
INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Spirit of Melbourne Dinner Cruise', 155 ,7,'Spend an evening on the Yarra River during this Melbourne dinner cruise. As you admire the twinkling city lights reflecting on the water, enjoy a 4-course gourmet meal inclusive of beverages. This fine dining experience includes beer, wine, and spirits, as well as coffee, tea, dessert, port, and a cheese plate. Cruise past attractions like Federation Square and the Royal Botanic Gardens while soaking up the elegant and relaxing atmosphere of the boat.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/37/fe/77.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Slumber Safari at Werribee Open Range Zoo', 345 ,7,'Go from the city streets of Melbourne to the African plains during a safari slumber experience at Werribee Open Range Zoo. This overnight experience provides luxury accommodation in a canvas tent that overlooks zoo’s African Savannah, and includes an evening night safari and gourmet meals.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0a/5e/0e/ee.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Great Ocean Road Reverse Itinerary Boutique Tour - Max 12 People', 118 ,7,'Experience the Great Ocean Road’s top attractions on this guided excursion that follows the iconic road in reverse. Embark on your journey and beat the crowds while learning about the region’s scenic landscapes and pretty coastal towns from an informative guide. Visit sites including the 12 Apostles, Loch Ard Gorge, Port Campbell, London Bridge, and Great Otway National Park Rainforest.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/96/95/a2.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Great Ocean Road Small-Group Ecotour', 135 ,7,'Take in breathtaking sights of long sandy beaches and dramatic cliffs on this guided, full-day tour of Australia’s Great Ocean Road. See some of the most spectacular coastal scenery on Earth, including the Twelve Apostles limestone stacks and Gibson`s Steps, site of historic cliff lines. Bushwalk in Great Otway National Park and try out your koala-spotting skills. Travel in a deluxe mini-coach with a small group for a relaxing, personalized experience.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/72/13/c9.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Yarra Valley Wine and Winery Tour', 150 ,7,'Experience the delights of Victoria’s wine country on this Yarra Valley wine tour from Melbourne. With an informative wine guide, you’ll visit four popular wineries: Balgownie Estate, Steels Gate Winery, Greenstone Vineyards, and Yering Farm. Enjoy plenty of tastings as well as a winery lunch while you learn about winemaking in Australian and admire the picturesque landscapes.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/72/12/fc.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Phillip Island Penguin, Brighton Beach, Moonlit Sanctuary', 140 ,7,'Discover the natural delights of Phillip Island with an eco-tour from Melbourne. See the iconic Brighton Beach bathing boxes, visit the beach and take some time to admire these historic landmarks. Visit the Moonlit Sanctuary Conservation Park for an up-close encounter with koalas and other Australian wildlife. Finish the day at a local beach where you can watch hundreds of some of the world`s tiniest penguins waddle out of the ocean and across the sand to their burrows.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0a/a4/8d/3d.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Melbourne Zoo General Entry Ticket', 40 ,7,'Spend a day immersed in the amazing animal kingdom at the Melbourne Zoo. Encounter native land species like koalas, wombats and kangaroos at the Australian Bush exhibit, and watch Victoria’s indigenous penguins and seals splash around at the Wild Sea. Admire creatures from around the globe, such as mighty Asian pachyderms at the Trail of Elephants and elegant African zebras and giraffes in open-air habitats. Don’t miss the energetic primates at Lemur Island and an elevated orangutan exhibit!', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/72/f5/6d.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Melbourne Balloon Flights, The Peaceful Adventure', 428 ,7,'A hot air balloon ride offers visitors to Melbourne a new perspective over one of the most beautiful cities in the country. This balloon flight experience is made extra special by departing at dawn, giving travelers stunning views of Melbourne’s cityscape as the sun rises, the perfect addition to an Australian holiday for those seeking something memorable.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0b/13/69/27.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('ArtVo Immersive Gallery Experience', 28 ,7,'Lose yourself in a sea of color at ArtVo, an interactive art space in The District Docklands, a short distance from the Melbourne CBD. As visitors explore more than 100 paintings across 11 themed zones, they are encouraged to touch and interact with the art. Take a selfie against angel wings or a backdrop of the Taj Mahal. Staff is on hand to help orient you and provide creative inspiration.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0b/8a/5b/ca.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Melbourne Walking Tour: Uncover Hidden Laneway Bars', 89 ,7,'Sip your choice of drinks on a "hidden" bar walking tour in Melbourne. Stroll with your guide to four locations for cocktails, Australian wine and beer, stopping into a classic pub, a speakeasy-style cocktail bar tucked into the laneway, a wine bar with options from the nearby Yarra Valley, and a fourth bar that will be selected by your guide depending on your group’s interests. You`ll learn about Melbourne`s bar scene and local history, and get tips for additional places to visit on your own.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0a/ef/aa/2f.jpg');

-- Sydney -- 
INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('All Inclusive Full-Day Blue Mountains Trip', 185 ,8,'Hit all the highlights of Australia`s Blue Mountains on this day tour from Sydney. View native Australian animals at Featherdale Wildlife Park, see the famous Three Sisters at Echo Park, then head for Scenic World (all three rides included). Wind up on a river cruise on the Parramatta back to Sydney for drop-off at Circular Quay or Darling Harbour. National Park fees and round-trip transportation from select hotels included.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/74/c5/f7.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Skyfeast at Sydney Tower', 90 ,8,'Soak in 360-degree views as you dine on a delicious buffet lunch or dinner at the Sydney Tower Restaurant`s revolving restaurant. From your vantage point high above the streets of Sydney, the views change as the restaurant slowly revolves during your meal. Large picture windows frame iconic sights like the Sydney Opera House, Sydney Harbour Bridge, Darling Harbour, Circular Quay and, in the distance, the Blue Mountains. Enjoy a lunch, dinner or even a degustation tasting a range of tasty dishes that is sure to please everyone in your party.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/07/8b/cd/64.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Blue Mountains Private Day Tour from Sydney with Wildlife Park and River Cruise', 240 ,8,'Convenient city hotel pick up in our SUV your PRIVATE fully guided tour ( min. 3 people) to the Blue Mountains World Heritage national park. Please ask for a special price for 4 or more people. Visiting the Featherdale Wildlife sanctuary for around one hour with all the native Australian animals - Koalas, Kangaroos and more. Seeing all the Mountains sights- The Grand Canyon, The 3 Sisters, Echo Point, Katoomba, Leura, Kattomba Falls, Orphan Rock, Cahill Lookout Aboriginal culture, visit Scenicworld to ride the Scenic Railway down to the forest Boardwalk and ride 2 Cablecars ( optional $49),and enjoy a relaxing River Cruise return to Sydney Harbour stepping off nearby the Opera house. Start about 8am return 5-6 pm ( Please email or phone the day before for hotel pick up time, phone number will appear on your ticket)', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/06/74/8f/f0.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Sydney Harbour Tour by Helicopter', 238 ,8,'Enjoy sweeping views of Sydney Harbour and beyond during a scenic helicopter flight over Sydney. Take to the skies for a quick flight that provides stunning panoramic views of Sydney’s eastern coastline including Coogee Beach, Bondi Beach, Manly Cove, Sydney’s spectacular Harbor and city skyline, the Sydney Harbour Bridge, and Sydney Opera House. Learn about the city’s history from your knowledgeable pilot as you fly along the coast of the Pacific Ocean before your pilot whirs over Sydney Head marking the harbor’s entrance.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0a/e3/7a/19.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Small-Group Hunter Valley Wine Tasting Tour', 175 ,8,'Fine-tune your appreciation of Australian wines and cuisine on this full-day tasting tour of the Hunter Valley from Sydney. Discover Australia`s oldest wine region with a behind-the-scenes winery tour and the chance to taste up to 20 wines at some of the valley’s most popular wineries. Restaurant lunch included.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0b/26/a9/eb.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Sydney Harbour Sunset Dinner Cruise', 99 ,8,'Enjoy a deluxe sunset cruise on Sydney Harbour accompanied by a delicious three-course dinner. From the water, admire iconic sights such as Sydney Harbour Bridge, Sydney Opera House, Fort Denison, Luna Park and more. Snap photos as the sky shimmers at sunset and the city skyline lights up for the night as you cruise through Sydney in the evening.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0b/33/d2/4d.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Sydney Harbour Jet Boat Thrill Ride: 30 Minutes', 89 ,8,'Blast off from Circular Quay on a jet boat ride that provides a super-fun 30-minute adrenaline-fueled ride along with a new perspective on Sydney`s most iconic waterside sights. Your expert captain slows down to give you a close up look at the Sydney Opera House, Sydney Harbour Bridge and other landmarks, then before zooming off again. Hang on as your jet boat executes 270-degree spins, power slides and other breathtaking maneuvers at high speed. Tours depart throughout the day, every hour.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/09/34/b0/32.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Hunter Valley Wine Tour from Sydney incl Lunch, Cheese, Chocolate and Distillery', 219 ,8,'Indulge your inner foodie as you discover the fine wines and culinary delights of Australia’s famous Hunter Valley. Set out from Sydney on a full-day small-group tour, stopping to enjoy tours and tastings at the region’s most prestigious boutique wineries. Along the way, tuck into lunch at a local restaurant, sample regional cheeses, and chocolates, and visit The Hunter Distillery.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0e/33/5c/ad.jpg');

INSERT INTO attractions (name, cost, cityID, details, imageLink) VALUES ('Journey Beyond Cruise Sydney Harbour - All inclusive Lunch Cruise', 182 ,8,'Experience one of the world`s most iconic destinations in style. Cruise around the beautiful Sydney Harbour and enjoy a premium dining experience. Seating just 90 people, this is the most stylish and unique way to discover the magic of Sydney Harbour. The three-course dinner menu features seasonal and regionally sourced food and wine from New South Wales.', 'https://media.tacdn.com/media/attractions-splice-spp-360x240/0a/78/a1/b7.jpg');
